import * as types from './../constants/ActionTypes';

var InitialState = [
    {
        memoID: "1",
        categoryID: "1",
        memoTitle: "Memo Title 1",
        memoContent: "Content 1",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: true,
        isDeleted: false,
    },
    {
        memoID: "2",
        categoryID: "1",
        memoTitle: "Memo Title 2",
        memoContent: "Content 2",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: true,
        isDeleted: false,
    },
    {
        memoID: "3",
        categoryID: "1",
        memoTitle: "Memo Title 3",
        memoContent: "Content 3",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: false,
        isDeleted: false,
    },
    {
        memoID: "4",
        categoryID: "1",
        memoTitle: "Memo Title 4",
        memoContent: "Content 4",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: false,
        isDeleted: false,
    },
    {
        memoID: "5",
        categoryID: "1",
        memoTitle: "Memo Title 5",
        memoContent: "Content 5",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: false,
        isDeleted: false,
    },
    {
        memoID: "6",
        categoryID: "2",
        memoTitle: "Memo Title 6",
        memoContent: "Content 6",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: false,
        isDeleted: false,
    },
    {
        memoID: "7",
        categoryID: "3",
        memoTitle: "Memo Title 7",
        memoContent: "Content 7",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: true,
        isDeleted: false,
    },
    {
        memoID: "8",
        categoryID: "3",
        memoTitle: "Memo Title 8",
        memoContent: "Content 8",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: true,
        isDeleted: false,
    },
    {
        memoID: "9",
        categoryID: "3",
        memoTitle: "Memo Title 9",
        memoContent: "Content 9",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: true,
        isDeleted: false,
    },
    {
        memoID: "10",
        categoryID: "3",
        memoTitle: "Memo Title 10",
        memoContent: "Content 10",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: false,
        isDeleted: false,
    },
    {
        memoID: "11",
        categoryID: "4",
        memoTitle: "Memo Title 11",
        memoContent: "Content 11",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: false,
        isDeleted: false,
    },
    {
        memoID: "12",
        categoryID: "5",
        memoTitle: "Memo Title 12",
        memoContent: "Content 12",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: true,
        isDeleted: false,
    },
    {
        memoID: "13",
        categoryID: "6",
        memoTitle: "Memo Title 13",
        memoContent: "Content 13",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: false,
        isDeleted: false,
    },
    {
        memoID: "14",
        categoryID: "7",
        memoTitle: "Memo Title 13",
        memoContent: "Content 14",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: true,
        isDeleted: false,
    },
    {
        memoID: "15",
        categoryID: "7",
        memoTitle: "Memo Title 13",
        memoContent: "Content 15",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: false,
        isDeleted: false,
    },
    {
        memoID: "16",
        categoryID: "7",
        memoTitle: "Memo Title 13",
        memoContent: "Content 16",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: true,
        isDeleted: false,
    },
    {
        memoID: "17",
        categoryID: "8",
        memoTitle: "Memo Title 13",
        memoContent: "Content 17",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: true,
        isDeleted: false,
    },
    {
        memoID: "18",
        categoryID: "9",
        memoTitle: "Memo Title 13",
        memoContent: "Content 18",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: true,
        isDeleted: false,
    },
    {
        memoID: "19",
        categoryID: "10",
        memoTitle: "Memo Title 13",
        memoContent: "Content 19",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: false,
        isDeleted: false,
    },
    {
        memoID: "20",
        categoryID: "11",
        memoTitle: "Memo Title 13",
        memoContent: "Content 20",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: false,
        isDeleted: false,
    },
    {
        memoID: "21",
        categoryID: "12",
        memoTitle: "Memo Title 13",
        memoContent: "Content 20",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: true,
        isDeleted: false,
    },
    {
        memoID: "22",
        categoryID: "13",
        memoTitle: "Memo Title 13",
        memoContent: "Content 20",
        memoDateCreated: new Date(),
        memoDeleteDate: new Date(),
        isClipped: false,
        isDeleted: false,
    },
];

const listMemo = (state = InitialState, action) => {
    switch (action.type) {
        case types.GET_QUESTIONS:
            state = action.data;
            return state;
        default:
            return state;
    }
};
export default listMemo;