export const GET_QUESTIONS = 'GET_QUESTIONS';
export const CHANGE_ISLOGIN = 'CHANGE_ISLOGIN';
export const CHANGE_ALLCATEGORY = 'CHANGE_ALLCATEGORY';
export const CHANGE_LISTMEMO = 'CHANGE_LISTMEMO';
export const CHANGE_MEMOSELECTED = 'CHANGE_MEMOSELECTED';
export const CHANGE_LISTMEMOSELECTED = 'CHANGE_LISTMEMOSELECTED';
